### PR TITLE
Several fixes to add/edit contact modal

### LINKED ISSUE #53: Dates cannot be saved in `Other information` data set
If you select a date data format in the `other information` data set, saving the contact is not going to work.

**Steps to reproduce:**

1. Edit a contact
2. Try to add an anniversary in the `other information` section
3. Click save
4. Notice it doesn't work.
5. Change the `anniversary` type to a `role` type
6. Click save
7. Notice saving still doesn't work
8. Remove the date info from the role textfield, write any other string and click save
9. Now saving works

**Example:**

### PR DESCRIPTION
**Pull request by econdepe**
- Closes #53.
- Takes care of a bug that would appear for contacts with UID in encrypted cards (put there by mistake)
- Make code more homogeneous

### CODE REVIEW

File: src/app/helpers/decrypt.js [hunk 1]
```diff
@@ -73,16 +73,23 @@ const ACTIONS = {
...
+    const decryptedCards = await Promise.all(
         Cards.map(async (card) => {
             if (!ACTIONS[card.Type]) {
                 return { error: FAIL_TO_READ };
             }
             return ACTIONS[card.Type](card, { publicKeys, privateKeys });
         })
     );
+    // remove UIDs put by mistake in encrypted cards
+    const sanitizedCards = decryptedCards.map(({ data }, i) => {
```
Comment (EpokK) [inline src/app/helpers/decrypt.js]: Where is `error`?

Comment (econdepe) [reply src/app/helpers/decrypt.js]: it should be there now
