### PR TITLE
Move merge reminder to the placeholder

### LINKED ISSUE #92: Merge reminder is not responsive
The blue reminder message that appears above the contact list is not responsive and looks broken on small-screen devices.

**Steps to reproduce:**

1. Go to contacts
2. Decrease your browser window in size until you reach the state shown in the screenshot
3. Notice the merge reminder text doesn't properly wrap

**Example:**

### PR DESCRIPTION
**Pull request by econdepe**
Proposal to move the merge reminder that used to be on top of the contact list to the placeholder, together with the import and export buttons:

image

Closes #92

### CODE REVIEW

**Comment by nico3333fr** [comment]
@econdepe maybe align the "more" button with the text?

**Comment by econdepe** [comment]
Things are aligned now thanks to @nico3333fr !

image

File: src/app/components/ContactRow.js [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+import ContactGroupIcon from './ContactGroupIcon';
+
+const ContactRow = ({ style, contactID, hasPaidMail, contactGroupsMap, contact, onClick, onCheck, onStop }) => {
+    const { ID, Name, LabelIDs = [], emails = [], isChecked } = contact;
+
+    return (
+        <div
+            style={style}
+            key={ID}
+            onClick={onClick(ID)}
```
Comment (EpokK) [inline src/app/components/ContactRow.js]: To avoid to define a function like `const handleClick => (ID) => () => {}`, I try to adapt it here:
```suggestion
            onClick={() => onClick(ID)}
```

File: src/app/containers/ContactsContainer.js [hunk 2]
```diff
@@ -163,12 +169,16 @@ const ContactsContainer = ({ location, history }) => {
...
         const currentContactID = getCurrentContactID();
         createModal(
-            <MergeModal contacts={beMergedContacts} contactID={currentContactID} userKeysList={userKeysList} />
+            <MergeModal contacts={mergeableContacts} contactID={currentContactID} userKeysList={userKeysList} />
         );
     };
+    const handleImport = () => createModal(<ImportModal userKeysList={userKeysList} />);
+    const handleExport = (contactGroupID) =>
+        createModal(<ExportModal contactGroupID={contactGroupID} userKeysList={userKeysList} />);
+    const handleGroups = () => history.push({ ...location, pathname: `/contacts/settings` });
```
Comment (EpokK) [inline src/app/containers/ContactsContainer.js]: Do you really need to pass `location` to settings state? `history.push('/contacts/settings')` is not enough?
If you really need it, please change:
```suggestion
    const handleGroups = () => history.push({ ...location, pathname: '/contacts/settings' });
```

File: src/app/components/MergeRow.js [hunk 3]
```diff
@@ -3,28 +3,33 @@ import PropTypes from 'prop-types';
...
-                <div className="bold">{c('Info').t`Two or more contacts appear to be identical.`}</div>
-                <div className="flex flex-items-center">
-                    <span className="mr0-5">{c('Info').t`Do you want to merge these contacts now?`}</span>
-                    <button type="button" className="color-white underline" onClick={onMerge}>
-                        {c('Action').t`Merge`}
-                    </button>
-                </div>
+            <div className="alignleft">
+                <span className="mr0-5">{c('Info').jt`${boldText} Do you want to merge these contacts now?`}</span>
+                <button
```
Comment (EpokK) [inline src/app/components/MergeRow.js]: You cannot use `Button` there?

File: src/app/components/ContactRow.js [hunk 4]
```diff
@@ -0,0 +1,75 @@
...
+            className={`item-container bg-global-white  ${contactID === ID ? 'item-is-selected' : ''}`}
+        >
+            <div className="flex flex-nowrap">
+                <span onClick={onStop}>
```
[the remark this answers is not in the document]
Comment (econdepe) [reply src/app/components/ContactRow.js]: Definitively possible. I was just preserving the old design, but indeed I believe a button makes more sense

File: src/app/containers/ContactsContainer.js (hunk 2 above)
Comment (econdepe) [reply src/app/containers/ContactsContainer.js]: It's actually necessary to clear the history in this case, so it should be `history.push('/contacts/settings')`!

**Comment by econdepe** [comment]
New design for the merge button:
image
