### PR TITLE
Fix sticky checkboxes on contact-groups dropdown

### LINKED ISSUE #110: Sticky checkboxes of contact groups
The checkboxes for the contact-group dropdowns do not behave as in v3. See flow below:

1) Open the dropdown for a contact
2) Toggle the checkbox for a given group
3) Close the dropdown
4) Re-open the dropdown.
5) The checkbox is as left after step 2, but it should be like in step 1 since no changes were applied. The state of the checkbox is remembered when it shouldn't.

Video: 
[sticky-checkbox.mkv.zip](https://github.com/ProtonMail/proton-contacts/files/3509807/sticky-checkbox.mkv.zip)

### PR DESCRIPTION
**Pull request by econdepe**
We must force the dropdown component to update upon closing

Fixes #110

### CODE REVIEW

File: src/app/components/ContactGroupDropdown.js [hunk 1]
```diff
@@ -140,7 +140,7 @@ const ContactGroupDropdown = ({ children, className, contactEmails, disabled })
 
     useEffect(() => {
         setModel(getModel(contactGroups, contactEmails));
```
Comment (EpokK) [inline src/app/components/ContactGroupDropdown.js]: In that case we could do
```suggestion
        isOpen && setModel(getModel(contactGroups, contactEmails));
```

Comment (econdepe) [reply src/app/components/ContactGroupDropdown.js]: That saves one `setState` and is more clear indeed
