### PR TITLE
Fix #60 - Improve import modal

### LINKED ISSUE #60: 'No csv or vcard file selected' error message when importing contacts
If you select any vcf or csv file, the import process is going to fail with the same error message: `no .csv or .vcard file selected`.

**Steps to reproduce:**

1. Click on import in contacts
2. Select any csv or vcf file
3. Notice the error and failed import process

**Screenshot:**

import failed

### PR DESCRIPTION
**Pull request by econdepe**
* Closes #60
* transform google csv into outlook csv
* generally retouch parsing of csv's

### CODE REVIEW

File: src/app/components/import/ImportCsvModalContent.js [hunk 1]
```diff
@@ -46,6 +46,7 @@ const ImportCsvModalContent = ({ file, onSetVcardContacts }) => {
     useEffect(() => {
         const parseFile = async () => {
             const preVcardsContacts = prepare(file);
+            console.log('prepared', preVcardsContacts);
```
Comment (EpokK) [inline src/app/components/import/ImportCsvModalContent.js]: remove it

Comment (econdepe) [reply src/app/components/import/ImportCsvModalContent.js]: oh, I fixed that but it seems I forgot to push, and then lint was not complaining for some reason...

File: src/app/components/import/ImportModal.js [hunk 2]
```diff
@@ -53,12 +54,13 @@ const ImportModal = ({ onClose, ...rest }) => {
     };
 
     const handleAttach = ({ target }) => {
-        const attachedFile = [...target.files].filter(({ type }) => ['text/vcard', 'text/csv'].includes(type))[0];
+        const ext = splitExtension(target.files[0].name)[1];
```
Comment (EpokK) [inline src/app/components/import/ImportModal.js]:
```suggestion
        const [ , ext] = splitExtension(target.files[0].name);
```

Comment (EpokK) [reply src/app/components/import/ImportModal.js]: what about adding a function that just returns the extension of the file? Sounds more logic no?

Comment (EpokK) [inline src/app/components/import/ImportModal.js]: I prefer to have verbose variable, use `extension` instead of `ext` which can be confusing with `external`.

Comment (econdepe) [reply src/app/components/import/ImportModal.js]: I'm using the function `splitExtension` in `components/import/AttachedFile` and I need the filename and the extension in there, so that's why it returns two elements. In general I think it can be useful to have the function behave as `split` and return an array. But if you think it's useful to create an additional `getExtension`, it can be done

Comment (econdepe) [reply src/app/components/import/ImportModal.js]: yep, I was actually not too happy myself with the choice...
