### PR TITLE
Fix #52 - handling of long name/emails

### LINKED ISSUE #52: Incorrect handling of contacts with long names and email addresses
If you have a contact with a long name or email addresses, certain elements are not going to be properly displayed.

- [x] The copy button in the contact viewer is missing its icon.

**Screenshot:**

missing copy button icon

- [x]  The email address goes behind the "Group / Settings" buttons:

long email overlap contact

- [x] The contact view screen allows horizontal scrolling beyond the bounds of the view:

overlap 2

### PR DESCRIPTION
**Pull request by nico3333fr**
## Short description of what this resolves:

- Incorrect handling of long name/emails
- bad display of button group (icon missing, etc.)

## Changes proposed in this pull request:

- wrapped buttons in a `flex-item-noshrink` to avoid it being shrinked (this part should not be flexible)
- added `ellipsis` class on elements to activate `text-overflow: ellipsis` when needed (added `title` attribute on mailto, best practice we always do when ellipsis is used)

Bonus : also fixed icon email display when long name, to avoid name being put under this icon

Fixes #52

image

🎉 (this is my first PR on React project, I really prefer this to Angular 👍  )

### CODE REVIEW

File: src/app/components/ContactSummary.js [hunk 1]
```diff
@@ -19,7 +19,14 @@ const ContactSummary = ({ properties }) => {
     const org = getFirstValue(properties, 'org');
 
     const summary = [
-        email && { icon: 'email', component: <a href={`mailto:${email}`}>{email}</a> },
+        email && {
+            icon: 'email',
+            component: (
+                <a href={`mailto:${email}`} title={`${email}`}>
```
Comment (EpokK) [inline src/app/components/ContactSummary.js]:
```suggestion
                <a href={`mailto:${email}`} title={email}>
```

File: src/app/components/ContactViewProperty.js [hunk 2]
```diff
@@ -23,7 +23,7 @@ const ContactViewProperty = ({ property, properties, contactID }) => {
             case 'email': {
                 return (
                     <>
-                        <a className="mr0-5" href={`mailto:${value}`}>
+                        <a className="mr0-5" href={`mailto:${value}`} title={`${value}`}>
```
Comment (EpokK) [inline src/app/components/ContactViewProperty.js]:
```suggestion
                        <a className="mr0-5" href={`mailto:${value}`} title={value}>
```
