### PR TITLE
Use date-fns

### LINKED ISSUE #311: App crash when too many fields are added
If you keep adding fields in the `Other information` section, eventually the app crashes.

**Env:**

Windows 10 x64
Chrome 78
1920x1080 @ 125%

**Example:**

3oxY23TLgE

### PR DESCRIPTION
**Pull request by econdepe**
The crash described in #331 was happening because we were using a deprecated version of the DateInput component in `react-components`, which has been recently changed as part of the migration to the `date-fns` library.

There were a few places in contacts where we were using `moment`. This PR migrates those uses to `date-fns`

Closes #311

### CODE REVIEW

File: src/app/components/ContactFieldProperty.js [hunk 1]
```diff
@@ -32,19 +32,10 @@ const ContactFieldProperty = ({ field, value, uid, onChange, ...rest }) => {
     }
 
     if (field === 'bday' || field === 'anniversary') {
-        const m = moment(value);
-        if (value === '' || m.isValid()) {
+        const date = value === '' ? toDate(Date.now()) : parseISO(value);
```
Comment (EpokK) [inline src/app/components/ContactFieldProperty.js]: What do you think about:
```suggestion
        const date = value === '' ? new Date() : parseISO(value);
```

File: src/app/components/ContactViewProperty.js [hunk 2]
```diff
@@ -61,9 +61,9 @@ const ContactViewProperty = ({
             return <a href={`tel:${value}`}>{value}</a>;
         }
         if (['bday', 'anniversary'].includes(field)) {
-            const date = moment(value);
-            if (date.isValid()) {
-                return date.format('LL');
+            const [date] = [parseISO(value), toDate(value)].filter(isValid);
+            if (date) {
+                return format(date, 'PP');
```
Comment (mmso) [inline src/app/components/ContactViewProperty.js]:
```js
import { dateLocale } from 'proton-shared/lib/i18n';
return format(date, 'PP', { locale: dateLocale });
```

File: src/app/components/ContactFieldProperty.js (hunk 1 above)
Comment (mmso) [reply src/app/components/ContactFieldProperty.js]: Yes have you considered using `new Date()` instead of `toDate`, I believe they function pretty much the same?

Comment (econdepe) [reply src/app/components/ContactFieldProperty.js]: Yeah, that's much better. It's what happens when you code before going to bed :sweat_smile:

File: src/app/components/ContactViewProperty.js (hunk 2 above)
Comment (econdepe) [reply src/app/components/ContactViewProperty.js]: Yep, forgot about that. Gonna add it in the `ContactKeysTable` also
