### PR TITLE
Fix disabled property of buttons in ContactToolBar

### LINKED ISSUE #108: Highlighted contacts cannot be added to contact groups
We fixed the delete button functionality when contact is opened but not selected (in https://github.com/ProtonMail/proton-contacts/issues/67), but now the `add to contact group` button in the toolbar has the same problem.

**Example:**

rILZwiF8ue

**Steps to reproduce:**

1. Open a contact but don't select it with the checkbox
2. Click the add to contact group button in the toolbar
3. Notice nothing happens

**Expected behavior:**

The add to contact group button should work like the delete button - highlighted contacts should be regarded as selected.

### PR DESCRIPTION
**Pull request by econdepe**
- The contact-groups dropdown was not clickable when a contact was selected but not checked.
- It was possible to click the 'delete' button when no contact was selected or checked, prompting some React errors.

Both things are fixed now.

Closes #108

### CODE REVIEW

**Comment by econdepe** [comment]
Indeed the fix was creating a different bug (contact group dropdown not getting the right contacts). It should be ok now

File: src/app/components/ContactToolbar.js [hunk 1]
```diff
@@ -4,24 +4,34 @@ import { Icon, Checkbox } from 'react-components';
...
 
-const ContactToolbar = ({ user, onCheck, onDelete, checked, checkedContacts, contactEmailsMap }) => {
+const ContactToolbar = ({ user, onCheck, onDelete, checked = false, contactID, checkedContacts, contactEmailsMap }) => {
+    // Include current contact as selected if none is checked
+    const activeContacts =
+        !!Object.values(checkedContacts).filter(Boolean).length || !contactID ? checkedContacts : { [contactID]: true };
+
     const handleCheck = ({ target }) => onCheck(target.checked);
 
     const contactEmailsSelected = useMemo(() => {
```
Comment (mmso) [inline src/app/components/ContactToolbar.js]: Could we move `contactEmailsSelected` out to `ContactsContainer` and use it in `handleDelete` and pass the selected contacts here as well so that they are using the same logic?

Comment (econdepe) [reply src/app/components/ContactToolbar.js]: Indeed. The component was looking like robocop...

Comment (mmso) [reply src/app/components/ContactToolbar.js]: Unfortunately I think you have to `useMemo` the activeIDs instead of calculating them on the fly due to performance in both places

File: src/app/containers/ContactsContainer.js [hunk 2]
```diff
@@ -93,38 +93,38 @@ const ContactsContainer = ({ location, history }) => {
...
+        return [];
+    }, [checkedContactIDs, location.pathname]);
+
+    if (loadingContactEmails || loadingContacts || loadingUserKeys || loadingContactGroups) {
+        return <Loader />;
+    }
 
     const handleDelete = async () => {
-        const contactIDs = getContactIDsToDelete();
+        const contactIDs = activeIDs();
```
Comment (mmso) [inline src/app/containers/ContactsContainer.js]:
```suggestion
        const contactIDs = activeIDs;
```

Comment (econdepe) [reply src/app/containers/ContactsContainer.js]: yeah, I forgot to retouch that since actually part of that logic is not needed anymore
