### PR TITLE
Free user can't access encrypted details on merge contact preview

### LINKED ISSUE #201: Contact preview in the merge modal displays encrypted details for a free user
With recent changes, a free user cannot either see nor add/modify any encrypted details of any contact. However, these details can be accessed from the merge modal, either by clicking on 
"contact details" in the dropdown menu, or by clicking on the contact preview.

image

This should not be the case. Instead, we should probably display the subscription panel as in #165

Also, both the contact details and merged contact preview are a bit broken after recent changes in the `design-system`

### PR DESCRIPTION
**Pull request by econdepe**
Fixes #201 

- [x] Add upsell panel for free user
- [x] Improve looks of the contact summary accessed from the merge modal

### CODE REVIEW

File: src/app/components/merge/MergeModal.js [hunk 1]
```diff
@@ -124,7 +125,8 @@ const MergeModal = ({ contacts, contactID, userKeysList, ...rest }) => {
 MergeModal.propTypes = {
     contacts: PropTypes.arrayOf(PropTypes.array).isRequired,
     contactID: PropTypes.string,
-    userKeysList: PropTypes.array.isRequired
+    userKeysList: PropTypes.array.isRequired,
+    hasPaidMail: PropTypes.oneOfType([PropTypes.number, PropTypes.bool])
```
Comment (EpokK) [inline src/app/components/merge/MergeModal.js]: It should be:
```suggestion
    hasPaidMail: PropTypes.bool
```
right?

Comment (econdepe) [reply src/app/components/merge/MergeModal.js]: You're right!

Comment (econdepe) [reply src/app/components/merge/MergeModal.js]: I took this from the `ContactRow` component, but after checking the `useUser` hook, I see that `hasPaidMail` is a number. I'll just transform it into a boolean through `!!hasPaidMail`
