### PR TITLE
More fixes to the PGP settings modal

### LINKED ISSUE #216: Encryption cannot be disabled for contacts
**Summary:**

If you upload a public key to a contact and enable encryption, disabling encryption afterwards is not possible.

Even after removing the public key, the encryption toggle stays enabled. The same happens with the sign toggle.

**Example:**

1uEunnrfSt

### PR DESCRIPTION
**Pull request by econdepe**
* keys were marked invalid incorrectly
* key model must be updated when keys are added

This fixes #216 , but I feel we need a more thorough review of the PGP settings modal. I think the code can be improved and some functionality is lacking (e.g. "set primary" button)

### CODE REVIEW

File: src/app/helpers/pgp.js [hunk 1]
```diff
@@ -42,7 +42,7 @@ export const allKeysExpired = async (keys = []) => {
     const keyObjects = keys.map((publicKey) => isExpiredKey(publicKey));
     const isExpired = await Promise.all(keyObjects);
 
-    return isExpired.some((keyExpired) => !keyExpired);
+    return !isExpired.some((keyExpired) => !keyExpired);
```
Comment (EpokK) [inline src/app/helpers/pgp.js]: This line can be improve, I'm seeing a double negation here.

Comment (econdepe) [reply src/app/helpers/pgp.js]: We can write
```
return isExpired.every((keyExpired) => keyExpired)
```
Although that's more clear syntax, I would say it's a better practice to use `!some`, because `every` has to check all the array entries, while `some` will return `true` as soon as one entry is `true`.

In this case it does not make a lot of a difference because `isExpired` should be a small array. I can change it if you think that's better
