### PR TITLE
Fix #91 - add exception for note display

### LINKED ISSUE #91: Notes are displayed as a single row element
Notes are usually at least a few rows long.

In v3 and in Outlook, long notes are fully displayed.

Currently, on v4, notes are displayed as a single-row element, which makes them not usable for a variety of causes.

Steps to reproduce:

1. Edit an existing contact
2. Add 2-3 paragraphs worth of lorem ipsum
3. Save the contact
4. Notice not much of the notes are displayed

**Example of current implementation:**

**Example on v3:**

v3

### PR DESCRIPTION
**Pull request by nico3333fr**
- added a function `applyEllipsisClass` with exceptions in order to manage notes display

image

Fixes: #91

### CODE REVIEW

File: src/app/components/ContactViewProperty.js [hunk 1]
```diff
@@ -105,11 +105,20 @@ const ContactViewProperty = ({ property, properties, contactID }) => {
...
+                return 'ellipsis';
+        }
+    };
+
     return (
         <Row>
             <ContactLabelProperty field={field} type={type} first={first} />
             <div className="flex flex-nowrap flex-items-center w100">
-                <span className="mr0-5 ellipsis">{getContent()}</span>
+                <span className={'mr0-5 flex-item-fluid ' + applyEllipsisClass()}>{getContent()}</span>
```
Comment (EpokK) [inline src/app/components/ContactViewProperty.js]: - Use `classnames` from component helper
- Add the condition in the `Array` itself:
```
<span className={classnames(['mr0-5 flex-item-fluid', !['note'].includes(field) && 'ellipsis'])}>{getContent()}</span>
```

Comment (nico3333fr) [reply src/app/components/ContactViewProperty.js]: Done with https://github.com/ProtonMail/proton-contacts/pull/101/commits/9c5b219439d415a040c72e42d0a8d485d184baae
